# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            James Beardsley
tagline:          'One cool customer'
description:      ''
baseurl:          http://beardsley-james.github.io/blog
url:              http://beardsley-james.github.io/blog
collections:      
  projects:
    output: true
timezone:         America/New_York

author:
  name:           'James Beardsley'
  url:            https://beardsley-james.github.io/
  email:          beards18@gmail.com

paginate:         5
gems:             [jekyll-paginate]

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/beardsley-james/blog